# fly.toml app configuration file generated for juliaskitchen on 2024-08-13T17:48:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'juliaskitchen'
primary_region = 'ord'

[build]

[[mounts]]
  source = 'juliamodels'
  destination = '/app/models'
  initial_size = '50gb'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'a100-40gb'
  memory = '32gb'
  cpu_kind = 'performance'
  cpus = 8
