# fly.toml app configuration file generated for julias-prep-station on 2024-08-14T15:51:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'julias-prep-station'
primary_region = 'ord'

[build]

[[mounts]]
  source = 'juliamodels'
  destination = '/app/models'
  initial_size = '50gb'

[http_service]
  internal_port = 8000
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'a100-40gb'
  memory = '32gb'
  cpu_kind = 'performance'
  cpus = 8
